# This example is based on the multi registry example provided by the build-push-action README, as well as this example at:
# https://github.com/docker/build-push-action/issues/239

# The upgrade guide from v1 to v2 may also be a valuable resource:
# https://github.com/docker/build-push-action/blob/master/UPGRADE.md
name: Push example

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Login to Quay
        uses: docker/login-action@v1 
        with:
          # be sure to add registry flag
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
	  push: true
          tags: ${{ github.sha }}
